name: main
on: [push, repository_dispatch, workflow_dispatch]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: '/home/runner/work/codemirror.next/codemirror.next/node_modules'
          key: ${{ runner.os }}-modules

      - run: node bin/cm.js install

      - run: npm test

      - run: node bin/cm.js build

      - uses: actions/upload-artifact@v2
        with:
          path: |
            autocomplete/dist/index.js
            basic-setup/dist/index.js
            closebrackets/dist/index.js
            collab/dist/index.js
            commands/dist/index.js
            comment/dist/index.js
            fold/dist/index.js
            gutter/dist/index.js
            highlight/dist/index.js
            history/dist/index.js
            lang-cpp/dist/index.js
            lang-css/dist/index.js
            lang-html/dist/index.js
            lang-java/dist/index.js
            lang-javascript/dist/index.js
            lang-json/dist/index.js
            lang-lezer/dist/index.js
            lang-markdown/dist/index.js
            lang-python/dist/index.js
            lang-rust/dist/index.js
            lang-ocaml/dist/index.js
            language/dist/index.js
            language-data/dist/index.js
            lang-xml/dist/index.js
            legacy-modes/dist/index.js
            lint/dist/index.js
            matchbrackets/dist/index.js
            panel/dist/index.js
            rangeset/dist/index.js
            rectangular-selection/dist/index.js
            search/dist/index.js
            state/dist/index.js
            stream-parser/dist/index.js
            text/dist/index.js
            theme-one-dark/dist/index.js
            tooltip/dist/index.js
            view/dist/index.js

